name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create Temporary CI Environment Variables
        run: |
          echo "DATABASE_URL=mysql2://root:password@db:3306/wiredsound_test" > .env
          echo "RAILS_ENV=test" >> .env

      - name: Build and Start Services
        run: docker compose up -d --build

      - name: Wait for Database
        run: sleep 20

      - name: Prepare Database
        run: docker compose run web bin/rails db:prepare --trace

      - name: Run Tests
        run: docker compose run web bin/rails test