name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Start Services
        run: docker-compose up -d

      - name: Wait for Database
        run: sleep 10

      - name: Prepare Database
        run: docker-compose run web bin/rails db:prepare

      - name: Run Tests
        run: docker-compose run web bin/rails test